### ISSUE TITLE
Error al crear usuario

### ISSUE THREAD

**Issue by LMarinBorges** [LMarinBorges/henry-pf#58]
Faltan checks en el frontend en caso de que la contraseña no pase validación. El backend devuelve un error de validación (la contraseña requiere al menos un carácter especial, un número, etc.) pero el frontend solo alerta al usuario que "ha habido un error al crear el usuario".

```js
{
  "state": "error",
  "message": "Error al crear el usuario"
}
```

**Comment by rojasxd2308** [comment]
se ha añadido la validación del contraseña del backend + la alerta en el frontend al realizar el inicio de sesión y registro de forma local
